import { SimulationPreset } from '../types/physics';

export const SIMULATION_PRESETS: SimulationPreset[] = [
  {
    id: 'eccentric_triple_95',
    name: 'Chaotic Three-Body Resonance (e = 0.95)',
    subtitle: 'Section 5.2 — Extreme High-Eccentricity Stress Test',
    description: 'Dense chaotic three-body interaction with extreme initial eccentricity e₀ = 0.95. Tests the K=16 dynamic Padé-Laplace reservoir during intense periastron delta kicks.',
    eccentricity: 0.95,
    pnOrder: '5.0PN_Memory',
    kSync: 2.5,
    betaSoftMin: 3.5,
    agents: [
      {
        id: 1,
        name: 'Compact Body α (Primary)',
        color: '#06b6d4', // cyan
        mass: 1.2,
        position: { x: -8.5, y: 0.4, z: 0.0 },
        velocity: { x: 0.02, y: -0.65, z: 0.0 },
        spin: { x: 0.0, y: 0.0, z: 0.8 },
        quadrupoleDef: 1.0,
        phase: 0.2,
        naturalFreq: 1.05,
      },
      {
        id: 2,
        name: 'Compact Body β (Secondary)',
        color: '#10b981', // emerald
        mass: 1.0,
        position: { x: 8.2, y: -0.5, z: 0.0 },
        velocity: { x: -0.03, y: 0.62, z: 0.0 },
        spin: { x: 0.0, y: 0.0, z: -0.6 },
        quadrupoleDef: 1.0,
        phase: 3.4,
        naturalFreq: 0.98,
      },
      {
        id: 3,
        name: 'Perturber γ (Eccentric Intruder)',
        color: '#f59e0b', // amber
        mass: 0.8,
        position: { x: 0.1, y: 15.0, z: 0.0 },
        velocity: { x: 0.45, y: -0.22, z: 0.0 },
        spin: { x: 0.4, y: 0.0, z: 0.5 },
        quadrupoleDef: 1.2,
        phase: 1.8,
        naturalFreq: 1.12,
      },
    ],
  },
  {
    id: 'memory_5pn_burst',
    name: '5.0PN Christodoulou Non-Linear Memory Burst',
    subtitle: 'Section 3.2 — Gravitational Wave Energy Flux Self-Interaction',
    description: 'High-velocity relativistic binary generating intense gravitational radiation. Demonstrates the permanent, non-oscillatory DC metric shift Δh^TT accumulated by non-linear memory.',
    eccentricity: 0.65,
    pnOrder: '5.0PN_Memory',
    kSync: 3.0,
    betaSoftMin: 4.0,
    agents: [
      {
        id: 1,
        name: 'Black Hole 1',
        color: '#38bdf8',
        mass: 1.5,
        position: { x: -6.0, y: 0.0, z: 0.0 },
        velocity: { x: 0.0, y: -0.85, z: 0.0 },
        spin: { x: 0.0, y: 0.0, z: 1.0 },
        quadrupoleDef: 1.0,
        phase: 0.0,
        naturalFreq: 1.2,
      },
      {
        id: 2,
        name: 'Black Hole 2',
        color: '#f43f5e',
        mass: 1.4,
        position: { x: 6.0, y: 0.0, z: 0.0 },
        velocity: { x: 0.0, y: 0.85, z: 0.0 },
        spin: { x: 0.0, y: 0.0, z: 0.9 },
        quadrupoleDef: 1.0,
        phase: 3.14,
        naturalFreq: 1.18,
      },
    ],
  },
  {
    id: 'kuramoto_curved_swarm',
    name: 'Riemannian Kuramoto Covariant Swarm (N=5)',
    subtitle: 'Section 2 — Curved-Manifold Geodesic Synchronization',
    description: 'Multi-agent synthetic swarm on a curved spatial slice (Σ, g). Parallel transports local phasors along minimizing geodesics to the Karcher barycenter q₀ to achieve global phase-locking.',
    eccentricity: 0.2,
    pnOrder: '3PN',
    kSync: 4.5,
    betaSoftMin: 3.0,
    agents: [
      {
        id: 1,
        name: 'Agent 1',
        color: '#06b6d4',
        mass: 0.9,
        position: { x: -7.0, y: -4.0, z: 0.0 },
        velocity: { x: 0.35, y: -0.3, z: 0.0 },
        spin: { x: 0, y: 0, z: 0.5 },
        quadrupoleDef: 1.0,
        phase: 0.5,
        naturalFreq: 1.1,
      },
      {
        id: 2,
        name: 'Agent 2',
        color: '#10b981',
        mass: 1.0,
        position: { x: 8.0, y: -3.0, z: 0.0 },
        velocity: { x: -0.2, y: 0.4, z: 0.0 },
        spin: { x: 0, y: 0, z: 0.5 },
        quadrupoleDef: 1.0,
        phase: 2.4,
        naturalFreq: 0.95,
      },
      {
        id: 3,
        name: 'Agent 3',
        color: '#f59e0b',
        mass: 0.8,
        position: { x: 1.0, y: 8.0, z: 0.0 },
        velocity: { x: -0.4, y: -0.1, z: 0.0 },
        spin: { x: 0, y: 0, z: 0.5 },
        quadrupoleDef: 1.0,
        phase: 4.8,
        naturalFreq: 1.02,
      },
      {
        id: 4,
        name: 'Agent 4',
        color: '#a855f7',
        mass: 0.9,
        position: { x: -5.0, y: 6.0, z: 0.0 },
        velocity: { x: 0.3, y: -0.4, z: 0.0 },
        spin: { x: 0, y: 0, z: 0.5 },
        quadrupoleDef: 1.0,
        phase: 1.2,
        naturalFreq: 1.08,
      },
      {
        id: 5,
        name: 'Agent 5',
        color: '#ec4899',
        mass: 1.1,
        position: { x: 6.0, y: 5.0, z: 0.0 },
        velocity: { x: -0.35, y: -0.2, z: 0.0 },
        spin: { x: 0, y: 0, z: 0.5 },
        quadrupoleDef: 1.0,
        phase: 5.5,
        naturalFreq: 0.92,
      },
    ],
  },
  {
    id: 'eob_plunge_ringdown',
    name: 'Braid Automaton Exchange & EOB Plunge',
    subtitle: 'Section 4 — Topological DFA & Kerr QNM Ringdown Sink',
    description: 'Close binary with an oscillating third body triggering topological braid crossings (B_N), followed by rapid radiation reaction driven plunge across the ISCO into the EOB S₄ sink.',
    eccentricity: 0.78,
    pnOrder: '5.0PN_Memory',
    kSync: 2.0,
    betaSoftMin: 4.2,
    agents: [
      {
        id: 1,
        name: 'Binary Core A',
        color: '#38bdf8',
        mass: 1.4,
        position: { x: -4.5, y: -1.0, z: 0.0 },
        velocity: { x: 0.1, y: -0.92, z: 0.0 },
        spin: { x: 0.0, y: 0.0, z: 0.7 },
        quadrupoleDef: 1.0,
        phase: 0.1,
        naturalFreq: 1.1,
      },
      {
        id: 2,
        name: 'Binary Core B',
        color: '#fb7185',
        mass: 1.3,
        position: { x: 4.5, y: 1.0, z: 0.0 },
        velocity: { x: -0.1, y: 0.92, z: 0.0 },
        spin: { x: 0.0, y: 0.0, z: -0.7 },
        quadrupoleDef: 1.0,
        phase: 3.2,
        naturalFreq: 1.08,
      },
      {
        id: 3,
        name: 'Interacting Strand C',
        color: '#34d399',
        mass: 0.7,
        position: { x: 0.0, y: 11.0, z: 0.0 },
        velocity: { x: 0.55, y: -0.35, z: 0.0 },
        spin: { x: 0.3, y: 0.2, z: 0.4 },
        quadrupoleDef: 1.1,
        phase: 1.9,
        naturalFreq: 0.98,
      },
    ],
  },
];
